version: '1'

services:
  user_authentication:
    build: /user_authentication
    command: ["node", "userAuthentication.ts"]
    container_name: authentication-container
    ports:
      - "80:80"
    networks:
      - microservices-network
  product_catalog:
    build: /product_catalog
    command: ["dotnet", "run", "ProductCatalog.cs"]
    image: mysql:latest
    container_name: catalog-container
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - microservices-network
  shopping_cart:
    build: /shopping_cart
    command: ["python", "shopping_cart.py"]
    container_name: shopping-cart-container
    ports:
      - "80:80"
    networks:
      - microservices-network
  payment_processing:
    build: /payment_processing
    command: ["java", "-jar", "paymentProcessing.jar"]
    container_name: payment-container
    ports:
      - "80:80"
    networks:
      - microservices-network
  order_fulfillment:
    build: /order_fulfillment
    command: ["ruby", "order_fulfillment.rb"]
    container_name: order-fulfillment-container
    ports:
      - "80:80"
    networks:
      - microservices-network

networks:
  microservices-network:
